### ISSUE TITLE
Sent email is absent in inbox when getting reply from Lavaboom

### ISSUE THREAD

**Issue by let4be** [lavab/api#142]
1. send email from Lavaboom to gmail
2. reply to this email from gmail
3. open reply in Lavaboom's inbox

What do I see? only reply is displayed
What expected to be seen? sent email, then reply

`emails.list` API request returns just one email
thread id: 7gxSMxbN1huFvFHCjgly

**Comment by pzduniak** [comment]
```panic: runtime error: index out of range

goroutine 422 [running]:
github.com/lavab/smtpd.parseAddress(0xc20814cbc5, 0x0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/lavab/mailer/Godeps/_workspace/src/github.com/lavab/smtpd/address.go:9 +0x34a
github.com/lavab/smtpd.(*session).handleMAIL(0xc2080c0370, 0xc20814cbc0, 0x3a, 0xc20814cbc0, 0x4, 0xc20823e6c0, 0x3, 0x3, 0xc20823a420, 0x2, ...)
        /gopath/src/github.com/lavab/mailer/Godeps/_workspace/src/github.com/lavab/smtpd/protocol.go:156 +0x13e
github.com/lavab/smtpd.(*session).handle(0xc2080c0370, 0xc20814cbc0, 0x3a)
        /gopath/src/github.com/lavab/mailer/Godeps/_workspace/src/github.com/lavab/smtpd/protocol.go:54 +0x338
github.com/lavab/smtpd.(*session).serve(0xc2080c0370)
        /gopath/src/github.com/lavab/mailer/Godeps/_workspace/src/github.com/lavab/smtpd/smtpd.go:213 +0xf7
github.com/lavab/smtpd.func·001()
        /gopath/src/github.com/lavab/mailer/Godeps/_workspace/src/github.com/lavab/smtpd/smtpd.go:159 +0x6e
created by github.com/lavab/smtpd.(*Server).Serve
        /gopath/src/github.com/lavab/mailer/Godeps/_workspace/src/github.com/lavab/smtpd/smtpd.go:164 +0x2e9```
probably that thing

_hilarious_

**Comment by andreis** [comment]
This is why I asked you to prioritize sorting out api and mailer bugs.

**Comment by pzduniak** [comment]
interesting, it's actually a pattern matching bug, not that address parser issue

**Comment by pzduniak** [comment]
i have absolutely no idea how the code worked earlier. fixed
