### ISSUE TITLE
SMTP library crash

### ISSUE THREAD

**Issue by pzduniak** [lavab/api#143]
```
panic: runtime error: index out of range

goroutine 422 [running]:
github.com/lavab/smtpd.parseAddress(0xc20814cbc5, 0x0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/lavab/mailer/Godeps/_workspace/src/github.com/lavab/smtpd/address.go:9 +0x34a
github.com/lavab/smtpd.(*session).handleMAIL(0xc2080c0370, 0xc20814cbc0, 0x3a, 0xc20814cbc0, 0x4, 0xc20823e6c0, 0x3, 0x3, 0xc20823a420, 0x2, ...)
        /gopath/src/github.com/lavab/mailer/Godeps/_workspace/src/github.com/lavab/smtpd/protocol.go:156 +0x13e
github.com/lavab/smtpd.(*session).handle(0xc2080c0370, 0xc20814cbc0, 0x3a)
        /gopath/src/github.com/lavab/mailer/Godeps/_workspace/src/github.com/lavab/smtpd/protocol.go:54 +0x338
github.com/lavab/smtpd.(*session).serve(0xc2080c0370)
        /gopath/src/github.com/lavab/mailer/Godeps/_workspace/src/github.com/lavab/smtpd/smtpd.go:213 +0xf7
github.com/lavab/smtpd.func·001()
        /gopath/src/github.com/lavab/mailer/Godeps/_workspace/src/github.com/lavab/smtpd/smtpd.go:159 +0x6e
created by github.com/lavab/smtpd.(*Server).Serve
        /gopath/src/github.com/lavab/mailer/Godeps/_workspace/src/github.com/lavab/smtpd/smtpd.go:164 +0x2e9
```

**Comment by pzduniak** [comment]
Not fixing it until I see it in Sentry :)

**Comment by pzduniak** [comment]
Ironically I have to rewrite the smtpd library to see it in Sentry.

**Comment by pzduniak** [comment]
Fixed anyways.
